login/urls.py
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 19 15:56:06 2019

@author: 蘇
"""

"""wakanda URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from . import views

#具体app下的url 配置

urlpatterns = [
    #正则表达式，注意其实和结束符之间的‘/’！！
    url(r'^$', views.login,name='login'),
    url(r'^register/', views.register,name='register'),
    url(r'^logout/', views.logout,name='logout'),
]
app_name = 'login'

wakanda/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from wakanda_forever import views
from django.conf.urls.static import static
from django.conf import settings


#项目Url的总路径
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wakanda/',include('wakanda_forever.urls',namespace='wakanda_forever')),
    url(r'^$',views.index ,name='index'),
    url(r'^comments/', include('comment.urls',namespace='comment')),
    url(r'^login/',include('login.urls',namespace='login')),
    url(r'ckeditor/', include('ckeditor_uploader.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #没有这一句无法显示上传的图片

login/models.py
from django.db import models

# Create your models here.


class User(models.Model):

    gender = (
        ('male', "男"),
        ('female', "女"),
    )

    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    sex = models.CharField(max_length=32, choices=gender, default="男")
    c_time = models.DateTimeField(auto_now_add=True)
    object=models.Manager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["c_time"]
        verbose_name = "用户"
        verbose_name_plural = "用户"

login/views.py
from django.shortcuts import render,redirect
from . import models
from .form import register_form
from .form import login_form


def login(request):
    if request.method == "POST":
        form = login_form(request.POST) # form 包含提交的数据
        if form.is_valid():# 如果提交的数据合法
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            try:
                user = models.User.object.get(name=username)
                print(user)
                if user.password == password:
                    request.session['username']=username
                    return redirect('/')
                else:
                    message = "密码不正确！请重新输入"
            except:
                    message = "用户名不存在！"      
    elif  "login_state" in request.session.keys() :
        return redirect('/')
    else:
        username='游客'
        form = login_form()
        
    return render(request, 'login/login.html', locals())


def register(request):
    if request.method == 'POST':# 当提交表单时   
        form = register_form(request.POST) # form 包含提交的数据
        if form.is_valid():# 如果提交的数据合法
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            password2 = form.cleaned_data['password2']
            email = form.cleaned_data['email']
            message = "请输入正确的信息" 
            if password!=password2:
                message = "确认密码不一致！请重新输入密码"
            else:
                try:
                    user = models.User.object.get(name=username)
                    print(user)
                    if user.name == username:
                        message = "用户名已存在！请重新输入用户名"
                except:
                    try:
                        user = models.User.object.get(email=email)
                        print(user)
                        message = "用户邮箱已存在！请重新输入邮箱地址"
                    except:
                        user = models.User()
                        user.name=username
                        user.password=password
                        user.email=email
                        user.save()
                        request.session['username']=username
                        return redirect('/')         
    elif  "login_state" in request.session.keys() :
        return redirect('/')
    else:
        username='游客'
        form = register_form()
        
    return render(request,'login/register.html',locals())

def logout(request):
    request.session['login_from'] = request.META.get('HTTP_REFERER', '/')
    url=request.session['login_from']
    # 清除当前对应session所有数据
    request.session.clear()

    return redirect(url)

login/templates/login/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>登陆页面</title>
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/icon" href="{% static 'login/assets/images/favicon.ico' %}"/>
    <!-- Font Awesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <!-- Bootstrap -->
    <!--"{% static 'login/assets/css/theme-color/default-theme.css' %}" -->
    <link href="{% static 'login/assets/css/bootstrap.min.css' %}"rel="stylesheet">
    <!-- Slick slider -->
    <link href="{% static 'login/assets/css/slick.css' %}" rel="stylesheet">
    <!-- Gallery Lightbox -->
    <link href="{% static 'login/assets/css/magnific-popup.css' %}" rel="stylesheet">
    <!-- Theme color -->
    <link id="switcher" href="{% static 'login/assets/css/theme-color/default-theme.css' %}" rel="stylesheet">

    <!-- Main Style -->
    <link href="{% static 'login/style.css' %}"  rel="stylesheet">
    <!-- Fonts -->

    <!-- Open Sans for body font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700,800" rel="stylesheet">
    <!-- Poppins for Title -->
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet"
 
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>
    
    <!-- Start Header -->
    <header id="mu-header" class="" role="banner">
        <div class="container">
            <nav class="navbar navbar-default mu-navbar">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

              <!-- Text Logo -->
              <a class="navbar-brand" href="/">Django</a>

              <!-- Image Logo -->
              <!-- <a class="navbar-brand" href="#"><img src="assets/images/logo.png"></a> -->


            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav mu-menu navbar-right">
                  <li><a href="/">主页</a></li>
                  <li><a href="/#mu-portfolio">文章</a></li>
                  <li><a href="#">{{username}} 你好呀:)</a></li>
                  {% if login_state %}
                    <li><a href="{% url 'login:logout' %}">注销</a></li>
                  {% else %}
                    <li><a href="/login">请登陆/注册</a></li>
                  {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
        </div>
    </header>
    <!-- End Header -->
    <section id="mu-featured-slider">
        <div class="container">
            <div class="row">

                    <div class="mu-featured-area">
                        <h1>欢迎登陆</h1>
                        <div class="mu-featured-content">
                            <p>登陆 or <a href="{% url 'login:register' %}">新用户注册</a>                       
                            </p>
                            {% if message %}
                            <div class="alert alert-warning">{{ message }}</div>
                            {% endif %}
                                <form class='form-login' method='post'>
                                    {% csrf_token %}
                                    {{ form }}
                                <p></p>
                                <input type="submit" class="mu-primary-btn view-my-work-btn" value="提交" />

                                </form>     
                        </div>
                    </div>
                </div>          
            </div>
        </div>
    </section>
    

    <!-- Start footer -->
    <footer id="mu-footer" role="contentinfo">
            <div class="container">
                <div class="mu-footer-area">
                    <p class="mu-copy-right">&copy; "Go and look again at the roses. You will understand now that yours is unique in all the world. Then come back to say goodbye to me, and I will make you a present of a secret." 
                </div>
            </div>

    </footer>
    <!-- End footer -->
    
 

    <!-- jQuery library -->
    <script src="https://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Bootstrap -->
    <!--"{% static 'login/assets/css/theme-color/default-theme.css' %}"-->
    <script src="{% static 'login/assets/js/bootstrap.min.js' %}"></script>
  <!-- Slick slider -->
    <script type="text/javascript" src="{% static 'login/assets/js/slick.min.js' %}"></script>
    <!-- Filterable Gallery js -->
    <script type="text/javascript" src="{% static 'login/assets/js/jquery.filterizr.min.js' %}"></script>
    <!-- Gallery Lightbox -->
    <script type="text/javascript" src="{% static 'login/assets/js/jquery.magnific-popup.min.js' %}"></script>
    <!-- Ajax contact form  -->
    <script type="text/javascript" src="{% static 'login/assets/js/app.js' %}"></script>
  <!-- Featured Slider -->
    <script type="text/javascript" src="{% static 'login/assets/js/typed.min.js' %}"></script>
    <!-- On scroll JS  -->
    <script src="{% static 'login/assets/js/jquery.appear.js' %}"></script>
  <!-- Progress Bar -->
    <script type="text/javascript" src="{% static 'login/assets/js/jquery.lineProgressbar.js' %}"></script>
    
  
    <!-- Custom js -->
  <script type="text/javascript" src="{% static 'login/assets/js/custom.js' %}"></script> 
</body>
</html>

login/templates/login/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>注册页面 </title>
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/icon" href="{% static 'login/assets/images/favicon.ico' %}"/>
    <!-- Font Awesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <!-- Bootstrap -->
    <!--"{% static 'login/assets/css/theme-color/default-theme.css' %}" -->
    <link href="{% static 'login/assets/css/bootstrap.min.css' %}"rel="stylesheet">
    <!-- Slick slider -->
    <link href="{% static 'login/assets/css/slick.css' %}" rel="stylesheet">
    <!-- Gallery Lightbox -->
    <link href="{% static 'login/assets/css/magnific-popup.css' %}" rel="stylesheet">
    <!-- Theme color -->
    <link id="switcher" href="{% static 'login/assets/css/theme-color/default-theme.css' %}" rel="stylesheet">

    <!-- Main Style -->
    <link href="{% static 'login/style.css' %}"  rel="stylesheet">
    <!-- Fonts -->

    <!-- Open Sans for body font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700,800" rel="stylesheet">
    <!-- Poppins for Title -->
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet"
 
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>
    
    <!-- Start Header -->
    <header id="mu-header" class="" role="banner">
        <div class="container">
            <nav class="navbar navbar-default mu-navbar">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

              <!-- Text Logo -->
              <a class="navbar-brand" href="/">Django</a>

              <!-- Image Logo -->
              <!-- <a class="navbar-brand" href="#"><img src="assets/images/logo.png"></a> -->


            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav mu-menu navbar-right">
                  <li><a href="/">主页</a></li>
                  <li><a href="/login">登陆/注册</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
        </div>
    </header>
    <!-- End Header -->
    <section id="mu-featured-slider">
        <div class="container">
            <div class="row">

                    <div class="mu-featured-area">
                        <h1>注册页面</h1>
                        <div class="mu-featured-content">
                            <p>请输入您的用户名 密码 邮箱 并选择性别进行注册                       
                            </p>
                            {% if message %}
                            <div class="alert alert-warning">{{ message }}</div>
                            {% endif %}
                                <form class='form-login' method='post'>
                                    {% csrf_token %}
                                    {{ form }}
                                <p></p>
                                <input type="submit" class="mu-primary-btn view-my-work-btn" value="提交" />

                                </form>     
                        </div>
                    </div>
                </div>          
            </div>
        </div>
    </section>
    <!-- Start footer -->
    <footer id="mu-footer" role="contentinfo">
            <div class="container">
                <div class="mu-footer-area">
                    <p class="mu-copy-right">&copy; "Go and look again at the roses. You will understand now that yours is unique in all the world. Then come back to say goodbye to me, and I will make you a present of a secret." 
                </div>
            </div>

    </footer>
    <!-- End footer -->
 

    <!-- jQuery library -->
    <script src="https://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Bootstrap -->
    <!--"{% static 'login/assets/css/theme-color/default-theme.css' %}"-->
    <script src="{% static 'login/assets/js/bootstrap.min.js' %}"></script>
  <!-- Slick slider -->
    <script type="text/javascript" src="{% static 'login/assets/js/slick.min.js' %}"></script>
    <!-- Filterable Gallery js -->
    <script type="text/javascript" src="{% static 'login/assets/js/jquery.filterizr.min.js' %}"></script>
    <!-- Gallery Lightbox -->
    <script type="text/javascript" src="{% static 'login/assets/js/jquery.magnific-popup.min.js' %}"></script>
    <!-- Ajax contact form  -->
    <script type="text/javascript" src="{% static 'login/assets/js/app.js' %}"></script>
  <!-- Featured Slider -->
    <script type="text/javascript" src="{% static 'login/assets/js/typed.min.js' %}"></script>
    <!-- On scroll JS  -->
    <script src="{% static 'login/assets/js/jquery.appear.js' %}"></script>
  <!-- Progress Bar -->
    <script type="text/javascript" src="{% static 'login/assets/js/jquery.lineProgressbar.js' %}"></script>
    
  
    <!-- Custom js -->
  <script type="text/javascript" src="{% static 'login/assets/js/custom.js' %}"></script> 
</body>
</html>