comment/urls.py
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 19 15:56:06 2019

@author: 蘇
"""

"""wakanda URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url

from comment import views
#具体app下的url 配置

urlpatterns = [
    #正则表达式，注意其实和结束符之间的‘/’！！
    url(r'^up_comment/', views.up_comment,name='up_comment'),
]
app_name = 'comment'

login/urls.py
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 19 15:56:06 2019

@author: 蘇
"""

"""wakanda URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from . import views

#具体app下的url 配置

urlpatterns = [
    #正则表达式，注意其实和结束符之间的‘/’！！
    url(r'^$', views.login,name='login'),
    url(r'^register/', views.register,name='register'),
    url(r'^logout/', views.logout,name='logout'),
]
app_name = 'login'

wakanda/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from wakanda_forever import views
from django.conf.urls.static import static
from django.conf import settings


#项目Url的总路径
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^wakanda/',include('wakanda_forever.urls',namespace='wakanda_forever')),
    url(r'^$',views.index ,name='index'),
    url(r'^comments/', include('comment.urls',namespace='comment')),
    url(r'^login/',include('login.urls',namespace='login')),
    url(r'ckeditor/', include('ckeditor_uploader.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #没有这一句无法显示上传的图片

wakanda_forever/urls.py
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 19 15:56:06 2019

@author: 蘇
"""

"""wakanda URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from . import views
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

#具体app下的url 配置
urlpatterns = [
    #正则表达式，注意其实和结束符之间的‘/’！！
    url(r'^article/(?P<article_id>[0-9]+)$',views.article_id,name='article_id'),
    url(r'^login/', views.login,name='login'),
#    url(r'^tools/scripts/(?P<script_id>[0-9]+)$',views.script_id,name='scripts')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #没有这一句无法显示上传的图片
app_name = 'wakanda_forever'

wakanda_forever/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField



class Tag(models.Model):
    tag=models.CharField(max_length=30)
    object=models.Manager()
    def __str__(self):
        return self.tag

class Author(models.Model):
    name=models.CharField(max_length=20)
    object=models.Manager()
    def __str__(self):
        return self.name
    
class Article(models.Model):
    article_title = models.CharField(max_length=100)
    article_content = RichTextUploadingField(default='')
    article_author = models.ForeignKey(Author,on_delete=models.CASCADE)
    article_tag = models.ForeignKey(Tag,on_delete=models.CASCADE)
    createtime = models.DateTimeField('保存日期',auto_now = True)
    object=models.Manager()
    def __str__(self):
        return self.article_title
    

wakanda_forever/views.py
from django.shortcuts import render
from .import models
from comment.models import Comment
from login import models as login_models
from django.shortcuts import redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



def index(request):
    tags=models.Tag.object.all()
    articles=models.Article.object.all()

    if "username" in request.session.keys():
        username=request.session['username']
        request.session['login_state'] = 1
        login_state=request.session['login_state']
    else:
        username='游客'  
    return render(request,'wakanda_forever/index.html',locals())


def login(request):
    request.session['login_from'] = request.META.get('HTTP_REFERER', '/')
    if request.method == "POST":
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        if username and password:  # 确保用户名和密码都不为空
            username = username.strip()
            # 用户名字符合法性验证
            # 密码长度验证
            #更多的其它验证.....
            try:
                user = login_models.User.object.get(name=username)
                request.session['username'] = username
                if user.password == password:
                   message='登陆成功,请留下您的评论' 
                   request.session['login_state'] = 1
                else:
                   message = "密码不正确！请重新输入"
            except:
                message = "用户名不存在！"
            request.session['message'] = message          
    return redirect(request.session['login_from'])

def article_id(request,article_id):
    article=models.Article.object.get(pk=article_id)
    
    if "login_state" in request.session.keys():
        username=request.session['username']
        login_state=request.session['login_state']
    else:
        username='游客'
        message='登陆后才能进行评论，请先登录' 
    
    comments=Comment.object.filter(content_type=article_id)  
    paginator = Paginator(comments, 5)
    page = request.GET.get('page')
    
    try:
        contacts = paginator.page(page) # contacts为Page对象！
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contacts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contacts = paginator.page(paginator.num_pages)
    return render(request,'wakanda_forever/content.html',locals())
 

wakanda_forever/templates/wakanda_forever/content.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <title>{{article.article_title}}</title>
  <link rel="shortcut icon" type="image/icon" href="{% static 'blog/assets/images/timg.jpg' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'content/res/layui/css/layui.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'content/res/css/main.css' %}">
  <!-- Open Sans for body font -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700,800" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">

<!--加载meta IE兼容文件-->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->
</head>
<body >
  <div class="header">
    <div class="menu-btn">
      <div class="menu"></div>
    </div>
    <h1 class="logo">
        <span>Django</span>
    </h1>
    <div class="nav">
      <a href="/">主页</a>
      <a href="/#mu-portfolio">文章</a>
      {% if login_state %}
        <a href="{% url 'login:logout' %}">注销</a>
      {% else %}
        <a href="/login">请登陆/注册</a>
      {% endif %}
      <a href="#mu-service">留言</a>
      <a >{{username}} 你好呀:)</a>
    </div>
    <!--ul class="layui-nav header-down-nav">
      <li class="layui-nav-item"><a href="index.html" class="active">a a a  文章</a></li>
      <li class="layui-nav-item"><a href="whisper.html">微语</a></li>
      <li class="layui-nav-item"><a href="leacots.html">留言</a></li>
      <li class="layui-nav-item"><a href="album.html">相册</a></li>
      <li class="layui-nav-item"><a href="about.html"  class="active">关于</a></li>
    </ul-->
  </div>


  <div class="content  whisper-content  leacots-content details-content">
    <div class="cont w1000">
      <div class="whisper-list">
        <div class="item-box">
          <div class="review-version">
              <div class="form-box">
                <div class="article-cont">
                  <div class="title" name="title">
                    <h3>{{article.article_title}}</h3>
                    <p class="cont-info"><span class="data">{{article.createtime}}</span>
                    <span>{{article.article_author}}</span>
                    <span class="types">{{article.article_tag}}</span>
                    </p>
                  </div>
                  {% autoescape off %}
                  <p>{{article.article_content}}</p>
                  {% endautoescape %}
                </div>

                {% if login_state  %}
                    <p></p>
                    {% if message %} 
                      <div class="alert alert-warning">{{ message }}</div>
                    {% endif %}
                  <div class="form">
                      <form class="layui-form" action="{% url 'comment:up_comment' %}" method="post">
                        <div class="layui-form-item layui-form-text">
                          <div class="layui-input-block">
                            <textarea name="desc" id="comment" placeholder="来都来了，那我......" class="layui-textarea"></textarea>
                          </div>
                        </div>
                        <div class="layui-form-item">
                          <div class="layui-input-block" style="text-align: right;">
                            <button class="layui-btn definite">確定</button>
                          </div>
                        </div>
                      </form>
                  </div>
                {% else %}
                  <div style="margin:0% 0%  ;">
                    <form action="{% url 'wakanda_forever:login' %}" method="post">
                      {% csrf_token %}
                      {% if message %}
                        <div class="alert alert-warning">
                          {{ message }}
                          <label for="id_username">用户名：</label>
                          <input type="text" id="id_username" name="username" placeholder="请输入您的用户名" autofocus required />
                          <label for="id_password">密码：</label>
                          <input type="password" id="id_password" placeholder="请输入您的密码" name="password" required >
                          <input type="submit" value="登陆">
                        </div>
                      {% endif %}
                    </form>
                  </div>
                {% endif %}
              </div>
              <p></p>
                
              <div class="volume">
                <section id="mu-service">
                        <div class="col-md-12">
                            <div class="mu-service-header">
                              <h2 class="mu-heading-title">全部留言</h2>
                              <span class="mu-header-dot"></span>
                            </div>
                        </div>
                </section>
              </div>

              <div class="list-cont">
                {% if comments %} 
                  {% for contact in contacts %}
                    <div class="cont">
                      <div class="text">
                        <p class="tit"><span class="name">{{contact.user_id}}</span><span class="data">{{contact.comment_time}}</span></p>
                        <p class="ct">{{contact.text }}</p>
                      </div>
                    </div>
                  {% endfor %}
                  <div class="pagination">
                    <span class="step-links">
                        {% if contacts.has_previous %}
                            <a href="?page={{ contacts.previous_page_number }}">上一页</a>
                        {% endif %}

                        <span class="current">
                            第{{ contacts.number }}页/共{{ contacts.paginator.num_pages }}页
                        </span>
                        {% if contacts.has_next %}
                            <a href="?page={{ contacts.next_page_number }}">下一页</a>
                        {% endif %}
                    </span>
                </div>
                {% else %}
                  <h5><center>暂无评论</center></h5>
                {% endif %}
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer id="mu-footer" role="contentinfo">
      <div class="container">
        <div class="mu-footer-area">
          <p class="mu-copy-right">&copy; 2019/04/16 So.Blog. Built using Django. Made by Junheng Su
        </div>
      </div>
  </footer>
</body>
</html>

wakanda_forever/templates/wakanda_forever/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>主页</title>
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/icon" href="{% static 'blog/assets/images/timg.jpg' %}"/>
    <!-- Font Awesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <!-- Bootstrap -->
    <!--"{% static 'blog/assets/css/theme-color/default-theme.css' %}" -->
    <link href="{% static 'blog/assets/css/bootstrap.min.css' %}"rel="stylesheet">
    <!-- Slick slider -->
    <link href="{% static 'blog/assets/css/slick.css' %}" rel="stylesheet">
    <!-- Gallery Lightbox -->
    <link href="{% static 'blog/assets/css/magnific-popup.css' %}" rel="stylesheet">
    <!-- Theme color -->
    <link id="switcher" href="{% static 'blog/assets/css/theme-color/default-theme.css' %}" rel="stylesheet">

    <!-- Main Style -->
    <link href="{% static 'blog/style.css' %}"  rel="stylesheet">
    <!-- Fonts -->

    <!-- Open Sans for body font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700,800" rel="stylesheet">
    <!-- Poppins for Title -->
  	<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
 
 
	
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  	
  	<!-- Start Header -->
	<header id="mu-header" class="" role="banner">
		<div class="container">
			<nav class="navbar navbar-default mu-navbar">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>

		      <!-- Text Logo -->
		      <a class="navbar-brand" >Django</a>
		      <!-- Image Logo -->
		      <!-- <a class="navbar-brand" href="#"><img src="assets/images/logo.png"></a> -->


		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      	<ul class="nav navbar-nav mu-menu navbar-right">
		          <li><a href="/">主页</a></li>
		          <li><a href="/#mu-portfolio">文章</a></li>
		          {% if login_state %}
		          	<li><a href="{% url 'login:logout' %}">注销</a></li>
		          {% else %}
		          	<li><a href="/login">请登陆/注册</a></li>
		          {% endif %}
		          <li><a >{{username}} 你好呀:)</a></li>
		      	</ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
		</div>
	</header>
	<!-- End Header -->

	<!-- Start Featured Slider -->

	<section id="mu-featured-slider">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="mu-featured-area">
						<h1>So Blog</h1>
						<!-- Start text slide -->
						<div class="mu-featured-slider-wrapper">
							<div class="mu-featured-slider" id="typed-strings">
								{% for tag in tags %}
									<p>目前有<span>{{tag.tag}}</span></p>
		   						{% endfor %}
							</div>
							<span id="typed"></span>
						</div>
						<!-- Start text slide -->
						
						<div class="mu-featured-content">
							<p>Once when I was six years old I saw a magnificent picture in a book, called True Stories from Nature, about the primeval forest. It was a picture of a boa constrictor in the act of swallowing an animal. Here is a copy of the drawing.n the book it said: "Boa constrictors swallow their prey whole, without chewing it. After that they are not able to move, and they sleep through the six months that they need for digestion."I pondered deeply, then, over the adventures of the jungle. And after some work with a colored pencil I succeeded in making my first drawing. My Drawing Number One. It looked like this:</p>
							<a href="#mu-portfolio" class="mu-primary-btn view-my-work-btn">浏览我的文章</a>
						</div>

					</div>
				</div>			
			</div>
		</div>
	</section>
	
	<!-- Start Featured Slider -->
	
	<!-- Start main content -->
		
	<main role="main">
		<!-- Start Portfolio -->
		<section id="mu-portfolio">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="mu-portfolio-area">
							<div class="mu-portfolio-header">
								<h2 class="mu-heading-title">全部文章</h2>
								<span class="mu-header-dot"></span>
							</div>

							<!-- Start Portfolio Filter -->
							<div class="mu-portfolio-filter-area">
								<ul class="mu-simplefilter">
					                <li class="active" data-filter="all">ALL</li>
					                {% for tag in tags %}
						                <li data-filter="{{tag.id}}">{{tag.tag}}</li>
						            {% endfor %}
					            </ul>
							</div>

							<!-- Start Portfolio Content -->
							<div class="mu-portfolio-content">
								<div class="filtr-container">
									{% for article in articles %}
					                <div class="col-xs-6 col-sm-4 col-md-4 filtr-item" data-category="{{article.article_tag_id}}">
					                	<div class="mu-item-thumbonail">
					                		<img class="img-responsive" src="https://www.sbkk88.com/uploads/allimg/150522/13444T5L-1.jpg" alt="image">
					                	</div>
					                	<div class="mu-filter-item-content">
					                    	<h4 class="mu-filter-item-title">{{article.article_title}}</h4>
					                    	<a class="mu-filter-link" href="{% url 'wakanda_forever:article_id' article.id %}" title="文章链接"><i class="fa fa-link"></i></a>
					                    	
					                    </div>
					                </div>
					                {% endfor %}
					            </div>
							</div>
							<!-- End Portfolio Content -->

						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End Portfolio -->

	<!-- Start footer -->
	<footer id="mu-footer" role="contentinfo">
			<div class="container">
				<div class="mu-footer-area">
					<p class="mu-copy-right">&copy; 2019/04/16 So.Blog. Built using Django. Made by Junheng Su
				</div>
			</div>

	</footer>
	<!-- End footer -->

	
	
    <!-- jQuery library -->
    <script src="https://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Bootstrap -->
    <!--"{% static 'blog/assets/css/theme-color/default-theme.css' %}"-->
    <script src="{% static 'blog/assets/js/bootstrap.min.js' %}"></script>
	<!-- Slick slider -->
    <script type="text/javascript" src="{% static 'blog/assets/js/slick.min.js' %}"></script>
    <!-- Filterable Gallery js -->
    <script type="text/javascript" src="{% static 'blog/assets/js/jquery.filterizr.min.js' %}"></script>
    <!-- Gallery Lightbox -->
    <script type="text/javascript" src="{% static 'blog/assets/js/jquery.magnific-popup.min.js' %}"></script>
    <!-- Ajax contact form  -->
    <script type="text/javascript" src="{% static 'blog/assets/js/app.js' %}"></script>
	<!-- Featured Slider -->
    <script type="text/javascript" src="{% static 'blog/assets/js/typed.min.js' %}"></script>
    <!-- On scroll JS  -->
    <script src="{% static 'blog/assets/js/jquery.appear.js' %}"></script>
	<!-- Progress Bar -->
    <script type="text/javascript" src="{% static 'blog/assets/js/jquery.lineProgressbar.js' %}"></script>
    
	
    <!-- Custom js -->
	<script type="text/javascript" src="{% static 'blog/assets/js/custom.js' %}"></script> 
  </body>
</html>